### ISSUE TITLE
Type.ToString is broken

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1242]
http://deck.net/c5e3f56b1eb0c5e4db7ed083ea735170
https://dotnetfiddle.net/PB7Onc

### Expected

```js
System.Int32
```

### Actual

``` js
function Class(){if(!(this instanceof Class)){var args=Array.prototype.slice.call(arguments,0),object=Object.create(Class.prototype),result=Class.apply(object,args);return typeof result==="object"?result:object;}
if(!initializing){if(this.$staticInit){this.$staticInit();}
if(this.$initMembers){this.$initMembers.apply(this,arguments);}
this.$$initCtor.apply(this,arguments);}}
```

### Steps To Reproduce

``` c#
public class App
{
    public static void Main()
    {
        int v = 2;
        Console.WriteLine(v.GetType().ToString());
    }
}
```

**Comment by geoffreymcgill** [comment]
This might be a tough one to change. The current result is the expected result in JavaScript. Calling .ToString() on any function will return the actual function source code.

If you need the name, how about using the `.FullName` property?

```javascript
v.GetType().FullName
```

**Comment by michaelcheers** [comment]
@geoffreymcgill, question? I don't see how it is a question. It is a behaviour which is different from .NET. [This](https://github.com/bridgedotnet/Bridge/issues/1345) is a defect and it is an issue about .NET and javascript ToString having different behaviours.

**Comment by geoffreymcgill** [comment]
I believe this scenario is working correctly as of Bridge 1.14. The return result will be `System.Int32` instead of `Bridge.Int32`.

**Comment by LeonidVeriga** [comment]
Yes, this one is fixed by #1337 as well.

**Comment by michaelcheers** [comment]
@geoffreymcgill, @geoffreymcgill, [Bridge Fiddle](http://live.bridge.net/#fca7b466f0fcf30f93d08de5e384c082) doesn't work.

**Comment by LeonidVeriga** [comment]
Right, it uses `System.Int32` as underlying type, that was fixed for 1.14, but `.toString()` is not defined.

**Comment by LeonidVeriga** [comment]
Related to #1335

**Comment by michaelcheers** [comment]
Type still isn't boxed so I think this issue should stay open, also ToString does not have the same behavior as FullName.

https://dev.deck.net/a6d9b30b78668e8998ee56a3da7ac2c2
https://dotnetfiddle.net/20L6fu

**Comment by serge-shaldanov** [comment]
Hi, guys.

It seems `typeof(T)` broken also:

Actual - Deck.Net: https://deck.net/13ce5c57e4284bd5fefa9eb09a074aa4

Expected - Ideone.com: https://ideone.com/1jKpgl

```csharp
public class Program
{
    public static void Main()
    {        
        // Expected:
        Console.WriteLine(typeof(string));
        var type = typeof(string);
        Console.WriteLine(type);
        
        // Not expected:
        Console.WriteLine("{0}", typeof(string));
        Console.WriteLine($"{typeof(string)}");
    }
}
```

Expected:

```
System.String
System.String
System.String
System.String
```

Actual:
```
System.String
System.String
function(){this.$initialize();u.$base&&(u.$$inherits&&u.$$inherits.length>0&&u.$$inherits[0].$staticInit&&u.$$inherits[0].$staticInit(),u.$base.ctor?u.$base.ctor.call(this):Bridge.isFunction(u.$base.constructor)&&u.$base.constructor.call(this))}
function(){this.$initialize();u.$base&&(u.$$inherits&&u.$$inherits.length>0&&u.$$inherits[0].$staticInit&&u.$$inherits[0].$staticInit(),u.$base.ctor?u.$base.ctor.call(this):Bridge.isFunction(u.$base.constructor)&&u.$base.constructor.call(this))}
```

It seems Bridge simply doesn't generate a call of `Bridge.getTypeName()` over the specified type when we call `typeof` from `string.Format` or from interpolated line.

I'm don't know should I create new issue or such case will be covered by current issue.
