### ISSUE TITLE
Wrong overloaded constructor call with optional parameters

### ISSUE THREAD

**Issue by AndreyZM** [bridgedotnet/Bridge#1511]
### Steps To Reproduce
http://live.bridge.net/#c1f5b459255d8ee9ee6c441652400efb
http://live.bridge.net/#e09431f7542bb5667d02bf623572e99b

Call to overloaded constructor produce:

```js
new Demo.App.SomeClass("constructor$1", );
```

**Comment by geoffreymcgill** [comment]
Hi @AndreyZM, thanks for reporting this problem. I think this might have been fixed with the latest source in **master**, although I have not tested yet to confirm. 

We will investigate.

**Comment by LeonidVeriga** [comment]
@vladsch, it's still reproducible with the latest code, it generates:
```
App.SomeClass.$constructor1();
```
