### ISSUE TITLE
Linq methods not compiled on Enumerable<ValueTuple>

### ISSUE THREAD

**Issue by hardhub** [bridgedotnet/Bridge#3728]
'First' method causes the compilation error.

### Steps To Reproduce

https://dev.deck.net/c93de56dcc0fdbce128171f1a6371a67

```csharp    public class Test : IEnumerable<(string Name, string Value)>
    {
        private readonly Dictionary<string, string> data = new Dictionary<string, string> { { "a1", "b1" }, { "a2", "b2" } };

        public IEnumerator<(string Name, string Value)> GetEnumerator()
        {
            foreach (KeyValuePair<string, string> pair in this.data)
            {
                yield return (pair.Key, pair.Value);
            }
        }
        IEnumerator IEnumerable.GetEnumerator()
        {
            return this.GetEnumerator();
        }
    }

    public class Program
    {
        public static void Main()
        {
            Test test = new Test();

            Console.WriteLine(test.First().Name);
        }
    }
```

### Expected Result

Expected result here
![image](https://user-images.githubusercontent.com/4306334/46203393-52c8dd00-c322-11e8-9f5c-fe9dd832c76b.png)

### Actual Result

```js
C# to JavaScript Compilation Failed

System.AggregateException: One or more errors occurred. ---> Bridge.Contract.EmitterException: Error parsing code.
E:\HostingSpaces\object\dev.deck.net\wwwroot\UserCode\u01szwxcpddf24hznqqldior.cs:48,67: Unexpected symbol `Name', expecting `.'
E:\HostingSpaces\object\dev.deck.net\wwwroot\UserCode\u01szwxcpddf24hznqqldior.cs:48,80: Unexpected symbol `Value', expecting `.'
E:\HostingSpaces\object\dev.deck.net\wwwroot\UserCode\u01szwxcpddf24hznqqldior.cs:48,99: Unexpected symbol `)', expecting `;' or `}'
   at Bridge.Translator.Translator.BuildSyntaxTreeForFile(Int32 index, String[]& rewriten)
   at Bridge.Translator.Translator.<>c__DisplayClass92_1.<BuildSyntaxTree>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Bridge.Translator.Translator.BuildSyntaxTree()
   at Bridge.Translator.Translator.Translate()
   at Deck.Translator.Translate(String& output)
   at Deck.TranslateHandler.Translate(String csCode, String filter, String pos)
---> (Inner Exception #0) Bridge.Contract.EmitterException: Error parsing code.
E:\HostingSpaces\object\dev.deck.net\wwwroot\UserCode\u01szwxcpddf24hznqqldior.cs:48,67: Unexpected symbol `Name', expecting `.'
E:\HostingSpaces\object\dev.deck.net\wwwroot\UserCode\u01szwxcpddf24hznqqldior.cs:48,80: Unexpected symbol `Value', expecting `.'
E:\HostingSpaces\object\dev.deck.net\wwwroot\UserCode\u01szwxcpddf24hznqqldior.cs:48,99: Unexpected symbol `)', expecting `;' or `}'
   at Bridge.Translator.Translator.BuildSyntaxTreeForFile(Int32 index, String[]& rewriten)
   at Bridge.Translator.Translator.<>c__DisplayClass92_1.<BuildSyntaxTree>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

**Comment by hardhub** [comment]
@geoffreymcgill 

Any updates on this?  
It is blocking issue for my code.  

It does not work with native collections as well:  

https://dev.deck.net/2dd9a1ed5cb19206fe548d9bda9c9b47

**Comment by fabriciomurta** [comment]
Hello @hardhub! Sorry for the delay in giving you a feedback but unfortunately, no news about this yet. I tried to quickly wrap the code in a working [dotnet fiddle](https://dotnetfiddle.net/) sample but it seems it'll require guessing necessary namespaces, or that's just not supported in dotnet fiddle either.

It may help to have a prompt native .net implementation, in any case.

**Comment by hardhub** [comment]
Hello @fabriciomurta @vladsch 

Yes, dotnet fiddle does not support ValueTuple.

I was able to run simple sample with native collections (from last comment) on Mono:  

https://repl.it/repls/NotableTepidCryptos

As you can see I have used console application to test original example.

**Comment by hardhub** [comment]
Just screenshot:

![image](https://user-images.githubusercontent.com/4306334/46580735-526fc680-ca33-11e8-9984-eaf3ded18fd5.png)

**Comment by fabriciomurta** [comment]
Fixed! This is going to be included in the next, 17.4.0, Bridge release!

**Comment by hardhub** [comment]
Thanks guys for help!

**Comment by hardhub** [comment]
I still getting this issue. Please check once again. You can open dev.deck link and it will fail.

**Comment by fabriciomurta** [comment]
Look at dev.deck.net timestamp; it says 20181004. My reply here was 20181007. :)
It is fixed in deck.net (release/final). It is just because we didn't push the same deck.net to dev.deck.net.

**Comment by hardhub** [comment]
@fabriciomurta I am still getting error in similar use cases.

https://deck.net/c4021b2961a298f1a754ad32048389ae

```C#
public sealed class Range : IEnumerable<(string A, float B)>
{
    private Dictionary<string, float> Values { get; } = new Dictionary<string, float>();

    public IEnumerator<(string A, float B)> GetEnumerator()
    {
        foreach (KeyValuePair<string, float> value in this.Values)
        {
            yield return (value.Key, value.Value);
        }
    }
    IEnumerator IEnumerable.GetEnumerator()
    {
        return this.GetEnumerator();
    }
}

public class Program
{
    public static void Main()
    {
        Range range = new Range();
        
        var test = range.Select(item => (object)item.B);
    }
}
```

**Comment by hardhub** [comment]
@fabriciomurta @vladsch 

Should this issue be reopened? I am about my previous comment with new sample.

**Comment by fabriciomurta** [comment]
Hello @hardhub, sorry for the delay.
As we already released a fix for the initially tested scenario and it works, I believe it would be best if we created a new issue. And then try to surround most (if not all) similar approaches to reproduce the issue in that one.

This would at least be sure which part of the fix went for which version.

**Comment by fabriciomurta** [comment]
The problem is now triggered just by the Select() call. I am guessing first case was due to the First() one.
`test.Select(item => (object)item.Value));`

**Comment by fabriciomurta** [comment]
@hardhub if already know some other Linq methods that are breaking, please update us in the new issue #3754 we've logged.

**Comment by hardhub** [comment]
Hi @fabriciomurta 

One more sample:

https://deck.net/01f5d7a73f1c9444afb5ef85dcd699f2

```C#
            (string Id, string Title)[] values = { ("a1", "b1"), ("a2", "b2") };

            Console.WriteLine(values.Any(item => item.Id == "a1"));
```
